import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Header from "@/components/home/navbar";
import Footer from "@/components/home/footer";
import { CartProvider } from "@/lib/context/cart-context";

// Load Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartProvider>
      <body className={poppins.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
      </CartProvider>
    </html>
  );
}
